### ISSUE TITLE
Implement/Document Choosing Only Specific Provider

### ISSUE THREAD

**Issue by naclander** [etu/webpaste.el#10]
Its currently not clear how to choose only 1 provider, for example.

I think its pretty common to only want to use `ix.io`, or only `ix.io` and `dpaste`, and nothing else. 

Briefly reading through `webpaste.el` I see changing the preference order is mentioned, but I think it would be good if this information was added to the README.

**Comment by etu** [comment]
Added this to it's own branch: https://github.com/etu/webpaste.el/tree/documentation-fixes#configuration

I will merge it later today when I have access to my gpg-key to sign the commit before putting it in master.

If you have additional suggestions I can add it as well :)

**Comment by naclander** [comment]
@etu Thanks so much!
