### ISSUE TITLE
Provider `ix.io` Broken

### ISSUE THREAD

**Issue by naclander** [etu/webpaste.el#15]
On a fresh install of webpaste, I did:

``` elisp
(setq webpaste-provider-priority '("ix.io"))
```
I then highlighted the region, and called `webpaste-paste-region` and I received:

``` elisp
Got error: (error http 400)
```

I tried briefly to figure out what post information requests is sending, but I couldn't figure it out.

Provider `sprunge` seems to work just fine, and I'm not seeing much difference in the implementations of these providers.

**Comment by etu** [comment]
I can reproduce this, that's odd. I'll have to dig into it later. According to their changelog on their website they haven't changed anything for a long time.

Also interesting that this doesn't paste to sprunge now that ix.io is broken:
```elisp
(setq webpaste-provider-priority '("ix.io" "sprunge.us"))
```

It prints with the error message from the error handler that should try again and end up at the second choice.

**Comment by naclander** [comment]
@etu Ok great, at least this error is reproducible.

Maybe we can also consider adding a test that attempt to paste to every provider available. This test should probably only be run manually as a sanity check and not as part of the regular unit tests as it would spam all the provider services way too much.

**Comment by etu** [comment]
That's a great idea. And it would be great to run it in the buildsystem once in a while. Travis can set env-variables and have periodic builds. It would be cool if one could detect if it's a periodic build and to set it to run once a week or once a month or something.

**Comment by naclander** [comment]
So I know the following snippet works and returns me a nice URL string:
``` emacs-lisp
(require 'request)
(request
 "http://ix.io"
 :type "POST"
 :data '(("f:i" . "hello"))
 :parser 'buffer-string
 :success (cl-function
           (lambda (&key data &allow-other-keys)
             (print data))))
```

But unforutnately I haven't figured out yet how to determine what webpaste is sending over in its evaluated data form, since there are a lot of nested compiled cl functions.

**Comment by etu** [comment]
Interesting... very interesting.

What I usually do for testing that is to send the request to a https://requestb.in/ to look at the output there... That way I can compare it to requests that I've "copied as curl" from my browsers.

**Comment by naclander** [comment]
@etu oh cool, that looks really useful.

**Comment by naclander** [comment]
RequestBin ended up being really useful. 

Didn't dig too much into it yet, but I have a suspicion `webpaste/providers-default-post-field-lambda` might be the culprit. 

RequestBin claims 
``` bash
curl -i -vvv -F 'f:1=hi' $URL 
```
returns **f:1**: hi as form parameters

Using webpaste I get the same thing, but with an additional parmeter of **nil**: text

Again, I haven't dug into this too much but I thought it might be useful.

**Comment by naclander** [comment]
Ok, so the bug lies in section inside `webpaste/providers-default-post-field-lambda`

``` emacs-lisp
;; Fetch alist of languages for this provider
(let ((provider-lang-alist (cdr (assoc provider-uri webpaste/provider-lang-alists))))
  ;; Fetch language name for this major mode for this provider
  (let ((language-name (cdr (assoc major-mode provider-lang-alist))))
    ;; If not set correctly, get the fundamental-mode one which should be plaintext
    (unless language-name
      (setq language-name (cdr (assoc 'fundamental-mode provider-lang-alist))))

    ;; Append language to the post-data
    (cl-pushnew (cons post-lang-field-name language-name) post-data)))
```

A bunch of defined providers  have `post-lang-field-name` set to nil ( default, since they dont' define it )
which causes this code to add a cons cell of `(nil . "text" )` to the request.  I think some providers handled an extra form field fine, while some providers ( `ix.io` ) barfed and returned `400` like we saw.

I think the correct thing to do if post-lang-field-name is set to nil is to skip this whole section entirely. 

As a side note, this was a pain to test due to the way this "function" was defined. Since it was a variable bound to to a cl-function I couldn't use edebug to trace it, and I had to restart emacs to load up the changes I made every time.

**Comment by etu** [comment]
Thank's for investigating this, it all looks good :)
