### ISSUE TITLE
[Question] Code Inconsistencies

### ISSUE THREAD

**Issue by naclander** [etu/webpaste.el#18]
I see various places where  you used `defvar` to define a variable as a `cl-function`.  This seems strange.

In other places though, I see you use `cl-defun`, which seems more correct. I'm not as familiar with `cl-macs.el` so I was wondering if you could explain to me the reasoning for not always using `cl-defun`.

**Comment by etu** [comment]
I mostly think it's me being terrible at elisp. I've tended to have stuff as variables if they are "constants" or something. Like, "predefined things".

But it also makes stuff hard to debug. It really would be better to make them functions that returns a lambda. And I just haven't got around to it...

**Comment by naclander** [comment]
Ok cool. I'm also learning elisp as I go. I just wanted to make sure you didn't have a reason not to use regular functions. 

I'll keep that in mind if I get around to refactoring.
