### ISSUE TITLE
Paste raw text

### ISSUE THREAD

**Issue by ghost** [etu/webpaste.el#25]
It would be great if paste was raw, no language formating, especially line numbers which make it hard to copy paste from the link properly.

**Comment by etu** [comment]
Should be easy to add an option for this. I've looked a bit shortly yesterday and I think something like this (but it's not finished yet). I also need to adjust the tests and so on: https://github.com/etu/webpaste.el/commit/ddae5cacd602252d041c92c6f6c7ee044c1f5e32

**Comment by etu** [comment]
This seems to work https://github.com/etu/webpaste.el/commit/cc158b5f6cb2155b69047ea52d8cb601b9615831, I should test it a bit more. Then I'll merge it :)
