### ISSUE TITLE
ptpb was discontinued

### ISSUE THREAD

**Issue by wandersoncferreira** [etu/webpaste.el#36]
> Due to continued write and egress abuse, ptpb.pw is now ~permanently shut
down. The current `pb` implementation has always been a toy at best, and is
unsuited for mitigating very real modern internet threats. Unchecked, current
usage would have resulted in $3000+/mo GCP bills for network egress--grossly
innapropriate for what has always been a charity project.

> See the following github issues for more information:

 - https://github.com/ptpb/pb/issues/245
 - https://github.com/ptpb/pb/issues/240

> In the future, ptpb.pw may be restored, but with an entirely new (possibly
backwards incompatible) API/implementation. This is months away, optimistically.

**Comment by etu** [comment]
Very sad news, thanks for the heads up. I've removed it in 7345c5f.

**Comment by etu** [comment]
I have now released 3.0.1 as a bug fix release to get this to melpa stable users as well.
