### ISSUE TITLE
Last commit broke webpaste-paste-buffer-or-region

### ISSUE THREAD

**Issue by AndreaOrru** [etu/webpaste.el#48]
https://github.com/etu/webpaste.el/commit/5e963e8ef17e937745b8f3b64f29690290c7a5c0 broke `webpaste-paste-buffer-or-region` for me.

I get this:
```
webpaste-paste-buffer-or-region: Wrong type argument: integer-or-marker-p, nil
```

**Comment by etu** [comment]
And before it was broken unless I selected a region first, and when a region had been activated and then deactivated it worked with both.

If you have an idea how to make both cases work, suggestions are welcome.
