### ISSUE TITLE
Webpaste tries providers in an infinite loop with no easy way to kill it

### ISSUE THREAD

**Issue by dsedivec** [etu/webpaste.el#49]
Today I happened to use a firewall to block outbound connections by webpaste, and webpaste went into an infinite loop of failures.  Excerpt from `*Messages*`:

```
...
[2020-08-28 15:25:45.160336] [error] request--callback: peculiar error
[2020-08-28 15:25:45.160560] Got error: (error . "exited abnormally with code 7
")
[2020-08-28 15:25:45.183091] [error] request--callback: peculiar error
[2020-08-28 15:25:45.183324] Got error: (error . "exited abnormally with code 7
")
[2020-08-28 15:25:45.205767] [error] request--callback: peculiar error
[2020-08-28 15:25:45.206004] Got error: (error . "exited abnormally with code 7
")
...
```

I eventually had to SIGUSR2 Emacs to stop it.  (Killing the timer might have worked, too, if I could do it 
between error messages.)

The docstring for `webpaste--paste-text` seems to indicate this is expected behavior?  "When we run out of providers to try, it will restart since ‘webpaste--tested-providers’ will be empty and then populated again."  But is it really ideal to have webpaste start spinning infinitely to paste, including spamming `*Messages*` and the minibuffer?  Obviously trying to use webpaste and then blocking all of its connections is dumb, but what if you accidentally trigger it when you're not connected to the Internet?

I suggest that webpaste should just go through the list of providers once, and just abort trying to create a paste after all providers fail.

Thank you for writing and maintaining this package!

**Comment by etu** [comment]
Hi!

I finally got around to looking into this. I was thinking about how to solve this yesterday and came up with e892ef243fb7bcf786d0994a59465868a6fb392e which is now in master.

One could think that one should only try each provider once. But it's not that simple, it was designed the way it is to do retries even if the user only have one provider enabled.

I hope this solves this issue :slightly_smiling_face:
