### ISSUE TITLE
Feature request: Ability to create anonymous gist

### ISSUE THREAD

**Issue by psibi** [etu/webpaste.el#8]
Ability to create anonymous public and secret gist.

Haven't looked at the API of github, but I think it should be possible.

**Comment by etu** [comment]
Will look into it when I get around to working on the project (probably some weekend). But PR's are always welcome :)

**Comment by etu** [comment]
I've been looking in to this, and it's not as simple as it sounds. But I've been doing a lot of refactoring to be able to have more ert-testing of the paste provider creation to be able to find regressions.

And with some work to replace how the parameters are built and sent to the provider, it should be easy. But I should make that bit more extensible and we're there.

I've also created the possibility to create providers that doesn't have failover, so they just fail instead. So if used for say github enterprise or other internal system, you can be sure it doesn't leak data.

There's also a function to paste to a specific provider so it should be possible to have your own wrapper function to do pastes to specific places.

**Comment by psibi** [comment]
@etu Thanks!
