### ISSUE TITLE
Private github gists?

### ISSUE THREAD

**Issue by pmetzger** [etu/webpaste.el#9]
Would it be straightforward to provide a customization so that one could use github gists with the private setting on (i.e. visible only to those with the URL)? Alternatively, one could provide two paste commands, for public and private pastebins. (For now, is it sufficient if I edit the code from `("public". "true")` to `("public". "false")`?)

**Comment by etu** [comment]
I prefer private over public, so I'm happy to change that. Will probably arrive on Wednesday this coming week at latest :)

Thanks for pointing it out.
